# -*- coding: utf-8 -*-
"""Final Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QtiX8f7wnZwz-eeaz2W4ClXcNatdqV9n
"""

import matplotlib.pyplot as plt

# Expense Tracker Project

expenses = {}

print("=================================")
print("      Expense Tracker")
print("=================================")

# Number of expense categories
n = int(input("Enter the number of expense categories: "))

# Input expense data
for i in range(n):
    category = input(f"\nEnter category {i+1}: ")
    amount = float(input(f"Enter amount for {category}: "))
    expenses[category] = amount

# Calculate total expense
total_expense = sum(expenses.values())

# Display expense summary
print("\n=================================")
print("       Expense Summary")
print("=================================")

for category, amount in expenses.items():
    print(f"{category}: ${amount:.2f}")

print("---------------------------------")
print(f"Total Expense: ${total_expense:.2f}")

# Find highest expense category
highest_category = max(expenses, key=expenses.get)
highest_amount = expenses[highest_category]

print(f"Highest Expense Category: {highest_category}")
print(f"Highest Expense Amount: ${highest_amount:.2f}")

# Pie Chart
plt.figure(figsize=(7, 7))
plt.pie(
    expenses.values(),
    labels=expenses.keys(),
    autopct="%1.1f%%"
)
plt.title("Expense Distribution")
plt.savefig("expense_pie_chart.png")
plt.show()

# Bar Chart
plt.figure(figsize=(8, 5))
plt.bar(
    expenses.keys(),
    expenses.values()
)
plt.title("Expense by Category")
plt.xlabel("Category")
plt.ylabel("Amount ($)")
plt.savefig("expense_bar_chart.png")
plt.show()

print("\nCharts saved successfully:")
print("- expense_pie_chart.png")
print("- expense_bar_chart.png")
